{% set version = "1.16.1" %}

package:
  name: automake
  version: {{ version }}

source:
  url: http://ftp.gnu.org/gnu/automake/automake-{{ version }}.tar.gz
  sha256: 608a97523f97db32f1f5d5615c98ca69326ced2054c9f82e65bade7fc4c9dea8
  patches:
     - 0001-apple-silicon.patch
     - 0002-apple-silicon.patch

build:
  number: 1004
  skip: true  # [win]

requirements:
  build:
    - make
  host:
    - m4
    - autoconf
    - perl *
    - make
  run:
    - m4
    - autoconf
    - perl *

test:
  commands:
    - automake --help

about:
  home: http://www.gnu.org/software/automake/
  license: GPL-3.0-or-later
  license_file: COPYING
  summary: Tool for automatically generating Makefile.in files compliant with the GNU Coding Standards.
  description: |
    Automake is a tool for automatically generating Makefile.ins from files
    called Makefile.am.  It assumes that the project uses Autoconf and enforces
    certain restrictions on the configure.ac contents.
  dev_url: https://git.savannah.gnu.org/git/automake.git
  doc_url: https://www.gnu.org/software/automake/manual/automake.html
  doc_source_url: http://git.savannah.gnu.org/cgit/automake.git/tree/doc

extra:
  recipe-maintainers:
    - jakirkham
    - ocefpaf
    - mingwandroid
